# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Sam Claridge
tagline:          'A Jekyll theme'
description:      'British transplant living in the American South, aspiring to create beautiful things. UI/UX designer.'
url:              http://hyde.getpoole.com


author:
  name:           'Sam Claridge'
  url:            https://twitter.com/samuelclaridge

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/samclaridge/samclaridge.github.io

gems:             [jekyll-paginate]
