# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        date

# Setup
title:            Sam Claridge
tagline:          'A Jekyll theme'
description:      'British transplant living in the American South, aspiring to create beautiful things. UI/UX designer.'
url:              http://hyde.getpoole.com


author:
  name:           'Sam Claridge'
  url:            https://twitter.com/samuelclaridge

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/samclaridge/samclaridge.github.io

gems:             [jekyll-paginate]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
